"""
schemas.py — Data models for Ecosystem Radar

All signals, actions, and digests flow through these structured models.
Pydantic is used so that we can validate LLM JSON output and get nice
IDE autocomplete / type-checking throughout the project.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from enum import Enum


class SignalType(str, Enum):
    COMPETITOR_MOVE   = "competitor_move"
    PARTNER_ANNOUNCE  = "partner_announcement"
    TECH_INTEGRATION  = "tech_integration"
    MARKETPLACE       = "marketplace_listing"
    JOINT_CUSTOMER    = "joint_customer_story"
    WEBINAR_EVENT     = "webinar_event"
    MSSP_MOTION       = "mssp_motion"
    CATEGORY_TREND    = "category_trend"
    UNKNOWN           = "unknown"


class Priority(str, Enum):
    HIGH   = "high"
    MEDIUM = "medium"
    LOW    = "low"


@dataclass
class RawPage:
    """Raw scraped content from a single URL."""
    url: str
    company_name: str
    company_type: str         # "competitor" | "partner" | "marketplace"
    fetched_at: str           # ISO timestamp
    title: str = ""
    text_content: str = ""    # cleaned body text
    links: list = field(default_factory=list)
    fetch_error: Optional[str] = None


@dataclass
class Signal:
    """
    A meaningful ecosystem signal extracted by the Interpreter agent.
    One RawPage can produce zero, one, or multiple Signals.
    """
    signal_id: str                          # deterministic hash of url+title
    company_name: str
    company_type: str                       # "competitor" | "partner"
    source_url: str
    signal_type: str                        # SignalType value
    title: str
    summary: str                            # 2-3 sentence plain-English summary
    why_it_matters: str                     # strategic implication for Obsidian
    detected_at: str                        # ISO timestamp
    publish_date: Optional[str] = None      # date from article if available
    related_partner: Optional[str] = None  # partner name if relevant
    affected_segment: Optional[str] = None # e.g. "Enterprise FSI", "Cloud SaaS"
    confidence: float = 0.7                 # 0.0 – 1.0
    priority: str = Priority.MEDIUM         # set by Ranker
    priority_score: float = 0.5             # 0.0 – 1.0, set by Ranker
    priority_rationale: str = ""            # set by Ranker
    is_new: bool = True                     # False if seen in a previous run


@dataclass
class ActionItem:
    """
    A concrete next action generated by the Activator agent for a Signal.
    """
    signal_id: str
    action_type: str          # e.g. "partner_outreach", "co_sell", "co_marketing", "internal_brief"
    description: str          # 1-2 sentence action description
    suggested_owner: str      # e.g. "Partner Manager", "AE", "Field Marketing"
    suggested_partners: list  # list of partner names to activate
    suggested_accounts: list  # account names or segments to target
    outreach_draft: Optional[str] = None   # optional Slack/email draft


@dataclass
class DigestEntry:
    """A Signal + its ActionItems, bundled for the digest."""
    signal: Signal
    actions: list   # list[ActionItem]


@dataclass
class Digest:
    """
    The final daily digest output — structured for Slack, email, or UI rendering.
    """
    generated_at: str
    run_id: str
    total_pages_scanned: int
    total_signals_found: int
    top_entries: list          # list[DigestEntry], max 5–7
    summary_narrative: str     # 2-3 sentence exec summary
    watchlist_coverage: dict   # {"competitor": N_scanned, "partner": N_scanned}
